name: EconomyPlus
main: EconomyPlus\EconomyPlus
version: 0.1.5
api: [2.0.0, 3.0.0-ALPHA1]
author: ImagicalGamer
permissions:
 economyplus.*:
  default: op
  description: Allows to control all of functions in EconomyPlus
  children:
     economyplus.command.takemoney:
      default: op
      description: Allows to take player's money
     economyplus.shop.create:
      description: Allows players to create shop signs
      default: op
     economyplus.shop.destroy:
      description: Allows players to destroy shop signs
      default: op
