---
# EconomyPlus Config File

# Money a player starts out with
Default-Money: 1000

# Default Language EconomyPlus Uses!
# Avalible Languages: "eng" or "english", "fre" or "french", "ger" or "german", "chi" or "chinese", "schi" or "simplified chinese", "rus" or "russian"
Default-Lang: "eng"


# Select how EconomyPlus data is stored! (JSON, or MySQL)
provider: JSON
# Enables the usage of MySQL!
# (If unable to connect to a server JSON will be used, EconomyPlus will dynamically update MySQL once connected)
mysql: [
  host: 127.0.0.1,
  port: 3303,
  user: economyplus,
  password: economyplus,
  db_name: economyplus_users
  ]

# Enable EconomyPlus Shop!
EnableShop: true
# Shop Format:
# [Shop]
# ItemId
# Amount
# Price

#Select a custom prefix for EconomyPlus shop signs (use @ to replace ยง)
ShopPrefix: '@7[@aShop@7]'

# Enable EconomyPlus Sell!
EnableSell: true
# Sell Format:
# [Sell]
# ItemId
# Amount
# Price

#Select a custom prefix for EconomyPlus sell signs (use @ to replace ยง)
SellPrefix: '@7[@bSell@7]'
...